/*
* generated by Xtext
*/
package com.jakecobb.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class IrisDatalogStandaloneSetup extends IrisDatalogStandaloneSetupGenerated{

	public static void doSetup() {
		new IrisDatalogStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

