/*
 * generated by Xtext
 */
package com.jakecobb.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IrisDatalogRuntimeModule extends com.jakecobb.dsl.AbstractIrisDatalogRuntimeModule {

}
